version: "3"

services:
  db: 
    container_name: back_db
    image: mysql:5.7
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: cube_solver
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports: 
      - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes: 
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "--password=password"]
      interval: 10s
      retries: 5

  server:
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    build: ./server/
    tty: true
    container_name: back_fastapi
    working_dir: /usr/src/server
    environment:
      DATABASE_URL: "mysql+pymysql://user:password@back_db/cube_solver"
    ports:
      - 8000:8000
    volumes:
      - ./server/code/:/usr/src/server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/visual"]
      interval: 10s
      retries: 5

  client:
    depends_on:
      server:
        condition: service_healthy
    build: ./client/
    container_name: front_react
    ports:
      - 3000:3000
    volumes:
      - ./server/:/var/www/server/
      - ./client/:/var/www/client/
    tty: true
    stdin_open: true
    command: sh -c "cd test_app && npm start"
